on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10name: Test
jobs:
  package:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get wails
      run: go get -u github.com/wailsapp/wails/cmd/wails
    - name: Build package osx
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        echo "building on ${{ matrix.platform }}"
        mkdir -p ~/.wails
        cp wails.json ~/.wails/
        wails build -p
      if: matrix.platform == 'macos-latest'
    - name: Build package linux
      run: |
        sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
        export PATH=${PATH}:`go env GOPATH`/bin
        echo "building on ${{ matrix.platform }}"
        mkdir -p ~/.wails
        cp wails.json ~/.wails/
        wails build
      if: matrix.platform == 'ubuntu-latest'
    - name: Build package windows
      run: |
        $GP = (go env GOPATH)
        setx path "%path%;%GP%"
        echo "building on ${{ matrix.platform }}"
        New-Item -ItemType directory -Path "$HOME\.wails" -Force
        Copy-Item -Path "$PWD\wails.json" -Destination "$HOME\.wails\wails.json"
        choco install mingw
        iex "$GP\bin\wails build -p"
      if: matrix.platform == 'windows-latest'